# Generated by Django 4.2.3 on 2023-07-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('раз', 'раз'), ('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=100, verbose_name='Периодичность'),
        ),
    ]
